In [ ]:
# English version of 
import numpy as np
# Ndarry object
# numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

## 1-dimension
a = np.array([1,2,3]) 
print(a)

## 2-dimension
b = np.array([[1, 2], [3, 4]]) 
print(b)

## set min dimension
c = np.array([1, 2, 3, 4, 5], ndmin = 2) 
print(c)
print(type(c[0][1]))

## set type of array
d = np.array([1, 2, 3], dtype = complex) 
print(d) 
print(type(d[1]))
print(type(d))

[1 2 3]
[[1 2]
 [3 4]]
[[1 2 3 4 5]]
<class 'numpy.int64'>
[1.+0.j 2.+0.j 3.+0.j]
<class 'numpy.complex128'>
<class 'numpy.ndarray'>


In [ ]:
# data type
# numpy.dtype(object, align, copy)
import numpy as np
dt1 = np.dtype(np.int32)
print(dt1)

dt2 = np.dtype('i4')
print(dt2)

dt3 = np.dtype('<i4')
print(dt3)


dt = np.dtype([('age', np.int8),('gender', np.bool_)])
a = np.array([(10),(20, False),(30)], dtype = dt)
print(a['age'])
print(a['gender'])
print(a)

student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
print(student)
a = np.array([('abc', 21, 50), ('xyz', 18, 75)])
print(a)
print(a[0])
print(type(a[0]))
print(a[0][0])
print(type(a[0][0]))

int32
int32
int32
[10 20 30]
[ True False  True]
[(10,  True) (20, False) (30,  True)]
[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[['abc' '21' '50']
 ['xyz' '18' '75']]
['abc' '21' '50']
<class 'numpy.ndarray'>
abc
<class 'numpy.str_'>


In [ ]:
# array attributes
import numpy as np

## ndim
a = np.arange(24)
print(a.ndim)
print(a)
## reshape
b = a.reshape(2,4,3)
print(b)
print(b.ndim)
## shape
c = np.array(([1, 2, 3], [4, 5, 6]))
print(c.shape)
c.shape = (3, 2)
c.shape = (3, -1)
c.shape = (3, 1, 2, 1)
print(c)
## itemsize()
x = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print(x.itemsize)
y = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(y.itemsize)
## flags
z = np.array([1, 2, 3, 4, 5])
print(z.flags)

1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3
(2, 3)
[[[[1]
   [2]]]


 [[[3]
   [4]]]


 [[[5]
   [6]]]]
8
1
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [ ]:
# create array

## numpy.empty(shape, dtype=float, order='C')
import numpy as np
x1 = np.empty([3, 2], dtype = np.int8)
print(x1)

## numpy.zeros(shape, dtype=float, order='C')
x2 = np.zeros(5)
print(x2)
x3 = np.zeros((5,), dtype = np.int8)
print(x3)
x4 = np.zeros((2, 2), dtype = [('x', 'i4'), ('y', 'i4')])
print(x4)

## numpy.ones(shape, dtype=float, order='C')
x5 = np.ones(5)
print(x5)
x6 = np.ones([2, 2], dtype =int)
print(x6)

[[10  0]
 [20  1]
 [30  1]]
[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


In [ ]:
# create array from existing list
# numpy.asarray(a, dtype=None, order=None)
import numpy as np
a1 = [1, 2, 3]
a2 = np.asarray(a1)
print(a1)
print(type(a1))
print(a2)
print(type(a2))
a3 = (1, 2, 3)
a3 = np.asarray(a3)
print(type(a3))
a4 = np.asarray(a1, dtype=float)
print(a4)

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
<class 'tuple'>
[1. 2. 3.]


In [ ]:
# create array from value range
# numpy.arange(start, stop, step, dtype)
import numpy as np
b1 = np.arange(5)
print(b1)
b2 = np.arange(5, dtype=float)
print(b2)
b3 = np.arange(10, 20 ,2)
print(b3)

# numpy.linespace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
b4 = np.linspace(1, 10, 10)
print(b4)
b5 = np.linspace(1, 1, 10)
print(b5)
b6 = np.linspace(10, 20, 5, endpoint = False)
print(b6)

# numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
b7 = np.logspace(0, 9, 10, base=2)
print(b7)
b8 = np.logspace(1.0, 2.0, num=10)
print(b8)

[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[10 12 14 16 18]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[10. 12. 14. 16. 18.]
[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [ ]:
# slice and index
import numpy as np
c1 = np.arange(10)
s1 = slice(2, 7, 2)
print(c1[s1])
print(c1[2:7:2])
print(c1[2])
print(c1[2:5])
print(c1[1:])

c2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(c2[...,1])
print(c2[1,...])
print(c2[...,1:])

c2 = np.array([[1, 2], [3, 4], [5, 6]])
c3 = c2[[0, 1, 2], [0, 1, 0]] # position: (0,0) (1,1) (2,0)
print(c3)
print(c1[c1 > 5])
c4 = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(c4[~np.isnan(c4)])
c5 = np.array([1, 2+6j, 5, 3.5+5j])
print(c5[np.iscomplex(c5)])

[2 4 6]
[2 4 6]
2
[2 3 4]
[1 2 3 4 5 6 7 8 9]
[2 5 8]
[4 5 6]
[[2 3]
 [5 6]
 [8 9]]
[1 4 5]
[6 7 8 9]
[1. 2. 3. 4. 5.]
[2. +6.j 3.5+5.j]


In [ ]:
# broadcast
import numpy as np
d1 = np.array([1, 2, 3, 4])
d2 = np.array([10, 20, 30, 40])
print(d1*d2)

d3 = np.array([1, 2, 3])
d4 = np.array([[0, 0, 0],
         [10, 10, 10],
         [20, 20, 20],
         [30, 30, 30]])
print(d3+d4)
print(np.tile(d3, (4, 1))+d4)

[ 10  40  90 160]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
# calculation function
import numpy as np
e1 = np.arange(9, dtype=np.float_).reshape(3,3)
e2 = np.array([10, 10, 10])
## add
print(np.add(e1, e2))
## subtract
print(np.subtract(e1, e2))
## multiply
print(np.multiply(e1, e2))
## divide
print(np.divide(e1,e2))
## reciprocal
print(np.reciprocal(e1))
## power
print(np.power(e1, 2))
print(np.power(e1, e2))
## mod
print(np.mod(e1, e2))
## reminder
print(np.remainder(e1, e2))

[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]
[[       inf 1.         0.5       ]
 [0.33333333 0.25       0.2       ]
 [0.16666667 0.14285714 0.125     ]]
[[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]]
[[0.00000000e+00 1.00000000e+00 1.02400000e+03]
 [5.90490000e+04 1.04857600e+06 9.76562500e+06]
 [6.04661760e+07 2.82475249e+08 1.07374182e+09]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: divide by zero encountered in reciprocal
  


In [ ]:
# statistics function
import numpy as np
f1 = np.array([[3, 7, 5], [8, 4, 3], [2, 4, 9]])
# min max
print(np.amin(f1,1))
print(np.amin(f1,0))
print(np.amax(f1))
print(np.amax(f1, axis=0))
# max - min
print(np.ptp(f1))
print(np.ptp(f1,1))
# median

[3 3 2]
[2 4 3]
9
[8 7 9]
7
[4 5 7]
