In [ ]:
import torch
from __future__ import print_function
x1 = torch.empty(3,5)
print(x1)

tensor([[6.7021e-15, 3.0674e-41, 3.3631e-44, 0.0000e+00,        nan],
        [3.0674e-41, 1.1578e+27, 1.1362e+30, 7.1547e+22, 4.5828e+30],
        [1.2121e+04, 7.1846e+22, 9.2198e-39, 7.0374e+22, 1.4285e-15]])


In [ ]:
x2 = torch.rand(3,5)
print(x2)

tensor([[0.1540, 0.4491, 0.9872, 0.9586, 0.4138],
        [0.9657, 0.2809, 0.0041, 0.1951, 0.5701],
        [0.1725, 0.2277, 0.7001, 0.1830, 0.1592]])


In [ ]:
x3 = torch.zeros(5, 3, dtype=torch.long)
print(x3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x4 = torch.tensor([5.5, 2, 4])
print(x4)
print(x3.size()[1])
print(x4.size())

tensor([5.5000, 2.0000, 4.0000])
3
torch.Size([3])


In [ ]:
x5 = torch.rand(3,5)
print(x5)
print(x2+x5)
print(torch.add(x2,x5))
print(x2.add_(x5))
print(x2)

tensor([[0.7071, 0.9743, 0.6411, 0.8200, 0.6905],
        [0.0250, 0.7285, 0.1571, 0.2349, 0.2318],
        [0.2448, 0.6999, 0.4718, 0.4293, 0.4372]])
tensor([[0.8612, 1.4234, 1.6283, 1.7786, 1.1042],
        [0.9907, 1.0094, 0.1611, 0.4300, 0.8019],
        [0.4173, 0.9276, 1.1719, 0.6124, 0.5964]])
tensor([[0.8612, 1.4234, 1.6283, 1.7786, 1.1042],
        [0.9907, 1.0094, 0.1611, 0.4300, 0.8019],
        [0.4173, 0.9276, 1.1719, 0.6124, 0.5964]])
tensor([[0.8612, 1.4234, 1.6283, 1.7786, 1.1042],
        [0.9907, 1.0094, 0.1611, 0.4300, 0.8019],
        [0.4173, 0.9276, 1.1719, 0.6124, 0.5964]])
tensor([[0.8612, 1.4234, 1.6283, 1.7786, 1.1042],
        [0.9907, 1.0094, 0.1611, 0.4300, 0.8019],
        [0.4173, 0.9276, 1.1719, 0.6124, 0.5964]])


In [ ]:
x = torch.randn(4, 4)
y = x.view(1, 16)
z = x.view(-1, 8)
print(x)
print(y)
print(z)

tensor([[-0.4494, -0.1511,  1.4316,  0.7217],
        [ 0.2014, -0.4539,  1.3184, -0.6097],
        [ 0.3903, -1.4452,  0.0817,  0.6180],
        [ 0.1492, -0.2159, -1.6099,  0.4989]])
tensor([[-0.4494, -0.1511,  1.4316,  0.7217,  0.2014, -0.4539,  1.3184, -0.6097,
          0.3903, -1.4452,  0.0817,  0.6180,  0.1492, -0.2159, -1.6099,  0.4989]])
tensor([[-0.4494, -0.1511,  1.4316,  0.7217,  0.2014, -0.4539,  1.3184, -0.6097],
        [ 0.3903, -1.4452,  0.0817,  0.6180,  0.1492, -0.2159, -1.6099,  0.4989]])


In [ ]:
print(torch.cuda.is_available())
x = torch.randn(1)
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', dtype=torch.double))

True
tensor([0.9900], device='cuda:0')
tensor([0.9900], dtype=torch.float64)


In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn)

z = y * y * 3
out = z.mean()
print(out.grad_fn)
print(z, out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [ ]:
a = torch.randn(2,2)
a = (a * 3)/(a - 1)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [ ]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [ ]:
a1 = torch.randn(3, requires_grad=True)
a2 = a1 * 2
while a2.data.norm() < 1000:
    a2 *= 2
print(a2)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
a2.backward(v)
print(a1.grad)

tensor([ -352.5476, -1245.2047,   459.7001], grad_fn=<MulBackward0>)
tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [ ]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
